import { callable } from "./decky";

// Callable esposte dal backend Python (main.py). Ricostruito dal dist.
const getSettings = callable("get_settings");
const saveSettings = callable("save_settings");
const getStatus = callable("get_status");
const debugLog = callable("debug_log");
const hideCurtain = callable("hide_curtain");
const showBlackCover = callable("show_black_cover");
const hideBlackCover = callable("hide_black_cover");
const setNativePromptVisible = callable("set_native_prompt_visible");
const launchRequested = callable("launch_requested");
const resolveGameLogo = callable("resolve_game_logo");
const getGameSettings = callable("get_game_settings");
const saveGameSettings = callable("save_game_settings");
const resetGameSettings = callable("reset_game_settings");
const validateLaunchImagePath = callable("validate_launch_image_path");
const getImagePreview = callable("get_image_preview");
const searchPlayStationGames = callable("search_playstation_games");
const getPlayStationBackgrounds = callable("get_playstation_backgrounds");
const applyPlayStationAsset = callable("apply_playstation_asset");
const removePlayStationAsset = callable("remove_playstation_asset");
const searchGoogleImages = callable("search_google_images");
const downloadGoogleImage = callable("download_google_image");
const searchIidbSoundbites = callable("search_iidb_soundbites");
const validateSoundbitePath = callable("validate_soundbite_path");
const getSoundbitePreview = callable("get_soundbite_preview");
const soundbiteRuntimeStarted = callable("soundbite_runtime_started");
const soundbiteRuntimeFinished = callable("soundbite_runtime_finished");
const importLocalSoundbite = callable("import_local_soundbite");
const downloadIidbSoundbite = callable("download_iidb_soundbite");
const clearSoundbite = callable("clear_soundbite");
const applyIidbSoundbite = callable("apply_iidb_soundbite");
const removeIidbSoundbite = callable("remove_iidb_soundbite");
const applyIidbAsset = callable("apply_iidb_asset");
const removeIidbAsset = callable("remove_iidb_asset");
const buildGameCache = callable("build_game_cache");
const cleanupUnusedLaunchImages = callable("cleanup_unused_launch_images");
const cleanupUnusedSoundbites = callable("cleanup_unused_soundbites");
const createBackup = callable("create_backup");
const restoreBackup = callable("restore_backup");
const startAutoMode = callable("start_auto_mode");
const stopAutoMode = callable("stop_auto_mode");
const FILE_SELECTION_FILE = 0;
const FILE_SELECTION_FOLDER = 1;

export { getSettings, saveSettings, getStatus, debugLog, hideCurtain, showBlackCover, hideBlackCover, setNativePromptVisible, launchRequested, resolveGameLogo, getGameSettings, saveGameSettings, resetGameSettings, validateLaunchImagePath, getImagePreview, searchPlayStationGames, getPlayStationBackgrounds, applyPlayStationAsset, removePlayStationAsset, searchGoogleImages, downloadGoogleImage, searchIidbSoundbites, validateSoundbitePath, getSoundbitePreview, soundbiteRuntimeStarted, soundbiteRuntimeFinished, importLocalSoundbite, downloadIidbSoundbite, clearSoundbite, applyIidbSoundbite, removeIidbSoundbite, applyIidbAsset, removeIidbAsset, buildGameCache, cleanupUnusedLaunchImages, cleanupUnusedSoundbites, createBackup, restoreBackup, startAutoMode, stopAutoMode, FILE_SELECTION_FILE, FILE_SELECTION_FOLDER };
