// i18n e stringhe localizzate (11 lingue). Ricostruito dal dist.
const I18N = {
    en: {
        curtain: "Curtain",
        automation: "Settings",
        timeout: "Timeout",
        foreground: "Foreground",
        showCurtain: "Show curtain",
        hideCurtain: "Hide curtain",
        launchInfo: "Launch info",
        launchMode: "Launch mode",
        modeModern: "Modern (in Steam UI)",
        modeClassic: "Classic (overlay window)",
        modeOff: "Off",
        focusSteam: "Focus Steam",
        autoLaunchCurtain: "Enable launch screen",
        windowsOnly: "Windows-only backend. This system is not Windows.",
        noForeground: "No foreground window detected",
        logo: "Logo",
        chooseLogo: "Choose custom logo",
        useDefaultLogo: "Use default logo",
        defaultLogo: "Default Playhub logo",
        customLogo: "Custom logo",
        logoPickerError: "Could not choose a logo.",
        timeoutEnabled: "Enable timeout",
        modeAuto: "Auto",
        forceMode: "Force mode for this game",
        gameTimeout: "Timeout only for this game",
        gameTimeoutSeconds: "Timeout duration",
        timeoutHelp: "How long the launch screen can stay visible while waiting for the game to become fullscreen.",
        timeoutDisabledHelp: "When disabled, the launch screen hides only after fullscreen detection or manual close.",
        exitDelay: "Exit delay",
        exitDelayHelp: "How long Launch Curtain stays visible after detecting that the game is ready.",
        seconds25: "25 seconds",
        seconds45: "45 seconds",
        seconds75: "75 seconds",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain needs attention"
    },
    it: {
        curtain: "Schermata",
        automation: "Impostazioni",
        timeout: "Timeout",
        foreground: "Finestra attiva",
        showCurtain: "Mostra schermata",
        hideCurtain: "Nascondi schermata",
        launchInfo: "Informazioni di lancio",
        launchMode: "Modalità di avvio",
        modeModern: "Moderna (nella UI di Steam)",
        modeClassic: "Classica (finestra overlay)",
        modeOff: "Disattivata",
        focusSteam: "Riporta Steam davanti",
        autoLaunchCurtain: "Attiva la schermata di avvio",
        windowsOnly: "Backend solo per Windows. Questo sistema non e Windows.",
        noForeground: "Nessuna finestra attiva rilevata",
        logo: "Logo",
        chooseLogo: "Scegli logo custom",
        useDefaultLogo: "Usa logo predefinito",
        defaultLogo: "Logo Playhub predefinito",
        customLogo: "Logo custom",
        logoPickerError: "Non sono riuscito a scegliere un logo.",
        timeoutEnabled: "Attiva timeout",
        modeAuto: "Automatica",
        forceMode: "Forza modalita per questo gioco",
        gameTimeout: "Timeout solo per questo gioco",
        gameTimeoutSeconds: "Durata timeout",
        timeoutHelp: "Per quanto tempo la schermata di avvio puo restare visibile mentre aspetta che il gioco passi a schermo intero.",
        timeoutDisabledHelp: "Se disattivo, la schermata si chiude solo quando rileva il fullscreen o con la chiusura manuale.",
        exitDelay: "Ritardo uscita",
        exitDelayHelp: "Per quanto tempo Launch Curtain resta visibile dopo aver rilevato che il gioco e pronto.",
        seconds25: "25 secondi",
        seconds45: "45 secondi",
        seconds75: "75 secondi",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain richiede attenzione"
    },
    fr: {
        curtain: "Rideau",
        automation: "Automatisation",
        timeout: "Delai",
        foreground: "Fenetre active",
        showCurtain: "Afficher le rideau",
        hideCurtain: "Masquer le rideau",
        launchInfo: "Infos de lancement",
        launchMode: "Mode de lancement",
        modeModern: "Moderne (dans l'UI Steam)",
        modeClassic: "Classique (fenêtre overlay)",
        modeOff: "Désactivé",
        focusSteam: "Remettre Steam devant",
        autoLaunchCurtain: "Rideau automatique au lancement",
        windowsOnly: "Backend Windows uniquement. Ce systeme n'est pas Windows.",
        noForeground: "Aucune fenetre active detectee",
        logo: "Logo",
        chooseLogo: "Choisir un logo personnalise",
        useDefaultLogo: "Utiliser le logo par defaut",
        defaultLogo: "Logo Playhub par defaut",
        customLogo: "Logo personnalise",
        logoPickerError: "Impossible de choisir un logo.",
        seconds25: "25 secondes",
        seconds45: "45 secondes",
        seconds75: "75 secondes",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain demande votre attention"
    },
    es: {
        curtain: "Cortina",
        automation: "Automatizacion",
        timeout: "Tiempo limite",
        foreground: "Ventana activa",
        showCurtain: "Mostrar cortina",
        hideCurtain: "Ocultar cortina",
        launchInfo: "Información de inicio",
        launchMode: "Modo de inicio",
        modeModern: "Moderno (en la interfaz de Steam)",
        modeClassic: "Clásico (ventana superpuesta)",
        modeOff: "Desactivado",
        focusSteam: "Enfocar Steam",
        autoLaunchCurtain: "Cortina automatica al iniciar",
        windowsOnly: "Backend solo para Windows. Este sistema no es Windows.",
        noForeground: "No se detecto ninguna ventana activa",
        logo: "Logo",
        chooseLogo: "Elegir logo personalizado",
        useDefaultLogo: "Usar logo predeterminado",
        defaultLogo: "Logo Playhub predeterminado",
        customLogo: "Logo personalizado",
        logoPickerError: "No se pudo elegir un logo.",
        seconds25: "25 segundos",
        seconds45: "45 segundos",
        seconds75: "75 segundos",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain necesita atencion"
    },
    pt: {
        curtain: "Cortina",
        automation: "Automacao",
        timeout: "Tempo limite",
        foreground: "Janela ativa",
        showCurtain: "Mostrar cortina",
        hideCurtain: "Ocultar cortina",
        launchInfo: "Informações de inicialização",
        launchMode: "Modo de inicialização",
        modeModern: "Moderno (na interface do Steam)",
        modeClassic: "Clássico (janela sobreposta)",
        modeOff: "Desligado",
        focusSteam: "Focar Steam",
        autoLaunchCurtain: "Cortina automatica ao iniciar",
        windowsOnly: "Backend apenas para Windows. Este sistema nao e Windows.",
        noForeground: "Nenhuma janela ativa detectada",
        logo: "Logotipo",
        chooseLogo: "Escolher logotipo personalizado",
        useDefaultLogo: "Usar logotipo padrao",
        defaultLogo: "Logotipo Playhub padrao",
        customLogo: "Logotipo personalizado",
        logoPickerError: "Nao foi possivel escolher um logotipo.",
        seconds25: "25 segundos",
        seconds45: "45 segundos",
        seconds75: "75 segundos",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain precisa de atencao"
    },
    "pt-br": {
        curtain: "Cortina",
        automation: "Automacao",
        timeout: "Tempo limite",
        foreground: "Janela ativa",
        showCurtain: "Mostrar cortina",
        hideCurtain: "Ocultar cortina",
        launchInfo: "Informações de inicialização",
        launchMode: "Modo de inicialização",
        modeModern: "Moderno (na interface do Steam)",
        modeClassic: "Clássico (janela sobreposta)",
        modeOff: "Desligado",
        focusSteam: "Focar Steam",
        autoLaunchCurtain: "Cortina automatica ao iniciar",
        windowsOnly: "Backend apenas para Windows. Este sistema nao e Windows.",
        noForeground: "Nenhuma janela ativa detectada",
        logo: "Logo",
        chooseLogo: "Escolher logo personalizado",
        useDefaultLogo: "Usar logo padrao",
        defaultLogo: "Logo Playhub padrao",
        customLogo: "Logo personalizado",
        logoPickerError: "Nao foi possivel escolher um logo.",
        seconds25: "25 segundos",
        seconds45: "45 segundos",
        seconds75: "75 segundos",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain precisa de atencao"
    },
    de: {
        curtain: "Vorhang",
        automation: "Automatisierung",
        timeout: "Zeitlimit",
        foreground: "Aktives Fenster",
        showCurtain: "Vorhang anzeigen",
        hideCurtain: "Vorhang ausblenden",
        launchInfo: "Startinfos",
        launchMode: "Startmodus",
        modeModern: "Modern (in der Steam-UI)",
        modeClassic: "Klassisch (Overlay-Fenster)",
        modeOff: "Aus",
        focusSteam: "Steam fokussieren",
        autoLaunchCurtain: "Automatischer Startvorhang",
        windowsOnly: "Backend nur fur Windows. Dieses System ist nicht Windows.",
        noForeground: "Kein aktives Fenster erkannt",
        logo: "Logo",
        chooseLogo: "Eigenes Logo wahlen",
        useDefaultLogo: "Standardlogo verwenden",
        defaultLogo: "Standard-Playhub-Logo",
        customLogo: "Eigenes Logo",
        logoPickerError: "Logo konnte nicht ausgewahlt werden.",
        seconds25: "25 Sekunden",
        seconds45: "45 Sekunden",
        seconds75: "75 Sekunden",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain braucht Aufmerksamkeit"
    },
    nl: {
        curtain: "Gordijn",
        automation: "Automatisering",
        timeout: "Time-out",
        foreground: "Actief venster",
        showCurtain: "Gordijn tonen",
        hideCurtain: "Gordijn verbergen",
        launchInfo: "Startinfo",
        launchMode: "Startmodus",
        modeModern: "Modern (in Steam-UI)",
        modeClassic: "Klassiek (overlayvenster)",
        modeOff: "Uit",
        focusSteam: "Steam naar voren",
        autoLaunchCurtain: "Automatisch startgordijn",
        windowsOnly: "Backend alleen voor Windows. Dit systeem is geen Windows.",
        noForeground: "Geen actief venster gevonden",
        logo: "Logo",
        chooseLogo: "Eigen logo kiezen",
        useDefaultLogo: "Standaardlogo gebruiken",
        defaultLogo: "Standaard Playhub-logo",
        customLogo: "Eigen logo",
        logoPickerError: "Kon geen logo kiezen.",
        seconds25: "25 seconden",
        seconds45: "45 seconden",
        seconds75: "75 seconden",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain vraagt aandacht"
    },
    uk: {
        curtain: "Завіса",
        automation: "Автоматизація",
        timeout: "Час очікування",
        foreground: "Активне вікно",
        showCurtain: "Показати завісу",
        hideCurtain: "Сховати завісу",
        launchInfo: "Інформація про запуск",
        launchMode: "Режим запуску",
        modeModern: "Сучасний (в інтерфейсі Steam)",
        modeClassic: "Класичний (вікно-оверлей)",
        modeOff: "Вимкнено",
        focusSteam: "Повернути Steam на передній план",
        autoLaunchCurtain: "Автоматична завіса запуску",
        windowsOnly: "Backend працює лише у Windows. Ця система не Windows.",
        noForeground: "Активне вікно не знайдено",
        logo: "Логотип",
        chooseLogo: "Вибрати власний логотип",
        useDefaultLogo: "Використати типовий логотип",
        defaultLogo: "Типовий логотип Playhub",
        customLogo: "Власний логотип",
        logoPickerError: "Не вдалося вибрати логотип.",
        seconds25: "25 секунд",
        seconds45: "45 секунд",
        seconds75: "75 секунд",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain потребує уваги"
    },
    zh: {
        curtain: "启动幕布",
        automation: "自动化",
        timeout: "超时",
        foreground: "前台窗口",
        showCurtain: "显示幕布",
        hideCurtain: "隐藏幕布",
        launchInfo: "启动信息",
        launchMode: "启动模式",
        modeModern: "现代（Steam 界面内）",
        modeClassic: "经典（叠加窗口）",
        modeOff: "关闭",
        focusSteam: "聚焦 Steam",
        autoLaunchCurtain: "启动时自动显示幕布",
        windowsOnly: "后端仅支持 Windows。当前系统不是 Windows。",
        noForeground: "未检测到前台窗口",
        logo: "标志",
        chooseLogo: "选择自定义标志",
        useDefaultLogo: "使用默认标志",
        defaultLogo: "默认 Playhub 标志",
        customLogo: "自定义标志",
        logoPickerError: "无法选择标志。",
        seconds25: "25 秒",
        seconds45: "45 秒",
        seconds75: "75 秒",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain 需要注意"
    },
    ja: {
        curtain: "カーテン",
        automation: "自動化",
        timeout: "タイムアウト",
        foreground: "前面のウィンドウ",
        showCurtain: "カーテンを表示",
        hideCurtain: "カーテンを非表示",
        launchInfo: "起動情報",
        launchMode: "起動モード",
        modeModern: "モダン（Steam UI内）",
        modeClassic: "クラシック（オーバーレイ）",
        modeOff: "オフ",
        focusSteam: "Steam を前面へ",
        autoLaunchCurtain: "起動時に自動表示",
        windowsOnly: "バックエンドは Windows 専用です。このシステムは Windows ではありません。",
        noForeground: "前面のウィンドウが見つかりません",
        logo: "ロゴ",
        chooseLogo: "カスタムロゴを選択",
        useDefaultLogo: "既定のロゴを使用",
        defaultLogo: "既定の Playhub ロゴ",
        customLogo: "カスタムロゴ",
        logoPickerError: "ロゴを選択できませんでした。",
        seconds25: "25 秒",
        seconds45: "45 秒",
        seconds75: "75 秒",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain に注意が必要です"
    }
};
const EXTRA_STRINGS = {
    en: {
        soundbites: "Soundbites", soundbitesHelp: "Play a short game-specific jingle while Launch Curtain is visible.", soundbiteVolume: "Soundbite volume", soundbiteMasterVolume: "Master Soundbite volume", soundbiteMasterVolumeHelp: "Applied on top of each game's individual Soundbite volume.", searchIidbSoundbites: "Search iiDB Soundbites", searchingIidbSoundbites: "Searching iiDB Soundbites...", noIidbSoundbites: "No iiDB Soundbites found.", previewSoundbite: "Preview", stopSoundbitePreview: "Stop preview", downloadApplySoundbite: "Download & apply", importSoundbite: "Import Soundbite", removeSoundbite: "Remove Soundbite", soundbiteLocal: "Local file", soundbiteIidb: "iiDB", soundbiteImported: "Local Soundbite imported.", soundbiteImportFailed: "Could not import the Soundbite.", soundbiteDownloadFailed: "Could not download the Soundbite.", playStationAssets: "PlayStation Assets", iidbAssets: "iiDB Assets", iidbSoundbites: "iiDB Soundbites", downloadIidbAssets: "Download iiDB Assets", removeIidbAssets: "Remove iiDB Assets", downloadingIidbAssets: "Downloading iiDB Assets", removingIidbAssets: "Removing iiDB Assets", bulkSoundbites: "Download missing iiDB Soundbites", removeIidbSoundbites: "Remove iiDB Soundbites", downloadingSoundbites: "Downloading Soundbites", removingSoundbites: "Removing iiDB Soundbites", showGamesWithoutSoundbites: "Show games without Soundbites", hideGamesWithoutSoundbites: "Hide games without Soundbites", showGamesWithSoundbites: "Show games with Soundbites", hideGamesWithSoundbites: "Hide games with Soundbites", manageSoundbiteExclusions: "Automatic Soundbite exclusions", soundbiteExclusionHelp: "Excluded games are skipped by automatic Soundbite assignment.", excluded: "Excluded", included: "Included", noGamesWithoutSoundbites: "All library games currently have a Soundbite or are excluded.", noGamesWithSoundbites: "No library games currently have a Soundbite.", playStationAssetProtectionHelp: "PlayStation Assets are applied only to installed games without an existing curtain. iiDB and manual/local assets are never replaced.", iidbAssetProtectionHelp: "iiDB Assets are applied only to games without an existing curtain. PlayStation and manual assets are never replaced.", bulkApplied: "Applied", bulkSkipped: "Skipped", bulkFailed: "Failed", bulkStop: "Stop", bulkStopped: "Stopped", iidb: "iiDB", assets: "Assets", yes: "Yes", no: "No", deleteUnusedSoundbites: "Delete unused Soundbites", cleanupUnusedSoundbitesFailed: "Could not remove unused Soundbites.", confirmRemovePlayStationAssets: "Remove all PlayStation-managed launch assets? Manually selected images and iiDB assets are preserved.", confirmRemoveIidbAssets: "Remove all iiDB-managed launch assets? PlayStation assets and manually selected images are preserved.", confirmRemoveIidbSoundbites: "Remove all iiDB-managed Soundbites currently assigned to games? Local Soundbites are preserved.", confirmDeleteUnusedSoundbites: "Delete only iiDB Soundbite files that are no longer assigned to any game? Local/imported files and active Soundbites are preserved.", confirmDeleteUnusedImages: "Delete only launch-image files in Launch Curtain's managed folder that are no longer used by any game?", whatToEdit: "What do you want to edit?", steamGridApiKey: "SteamGridDB API key", steamGridApiHelp: "SteamGridDB Hero search uses your personal API key. Launch Curtain does not bundle an API key.", steamGridApiPage: "Open SteamGridDB API page", steamGridCredits: "SteamGridDB Hero artwork is provided through the SteamGridDB API and remains third-party content.", iisuCredits: "Special thanks to the iiSU team and community for creating iiDB and for the incredible work behind its growing collection of game artwork and soundbites. Their passion for presentation, preservation, and beautifully curated game assets has made Launch Curtain’s iiDB integration possible. Huge thanks for building such a valuable resource for the gaming community and for making these assets accessible to projects like this one.", steamGridApiPlaceholder: "Paste your personal API key", saveSteamGridApiKey: "Save SteamGridDB API key", steamGridApiSaved: "SteamGridDB API key saved.", steamGridApiCleared: "SteamGridDB API key cleared.", steamGridApiSaveFailed: "Could not save the SteamGridDB API key.", steamGridApiRequired: "Configure your personal SteamGridDB API key in the Launch Curtain QAM before searching.", steamGridHeroOnlyHelp: "SteamGridDB search returns Hero artwork only.",
        maintenance: "Maintenance", refreshGameCache: "Refresh game cache", deleteUnusedImages: "Delete unused images", backup: "Backup", backupHelp: "Create or restore a complete backup of Launch Curtain settings, curtains, Soundbites and referenced local files. The backup also contains saved service settings such as your SteamGridDB API key.", createBackup: "Create backup", restoreBackup: "Restore backup", backupCreated: "Backup created in", backupRestored: "Backup restored successfully.", backupFailed: "Could not create the backup.", restoreBackupFailed: "Could not restore the backup.", backupMissingFiles: "Some external files could not be included.", confirmRestoreBackup: "Restore this backup? Current Launch Curtain settings and managed files will be replaced. A temporary rollback copy is created automatically before the restore.",
        downloadPlayStationAssetsInstalled: "Download PS assets for installed games", noInstalledGames: "No installed Steam games were found.",
        downloadPlayStationAssets: "Download PlayStation assets", removePlayStationAssets: "Remove PlayStation assets", downloadingPlayStationAssets: "Downloading PlayStation assets", removingPlayStationAssets: "Removing PlayStation assets", playStationBulkApplied: "Applied", playStationBulkRemoved: "Removed", playStationBulkSkipped: "Skipped", playStationBulkFailed: "Failed", playStationBulkError: "The PlayStation bulk operation could not be completed",
        tabGame: "Game", tabAppearance: "Appearance", tabScrapers: "Scrapers",
        gameBehavior: "Launch Curtain behavior", gameBehaviorHelp: "Choose how Launch Curtain behaves for this game.", enableForGame: "Enable Launch Curtain for this game",
        logoHelp: "Control the game logo and open the visual editor.", showLogo: "Show logo", openEditor: "Open Editor", logoZoom: "Enable logo zoom-in animation", bgZoom: "Enable background zoom-out animation",
        launchImage: "Launch image", noLaunchImage: "No launch image selected", chooseLaunchImage: "Choose fullscreen launch image", clearLaunchImage: "Clear launch image",
        editorTitle: "Editor", close: "Close", saving: "Saving...", editorSaveFailed: "Could not save the editor settings.", backgroundOpacity: "Background opacity", logoShadowOpacity: "Logo shadow opacity", logoShadowBlur: "Logo shadow blur", up: "Up", down: "Down", left: "Left", right: "Right", reset: "Reset", smaller: "Smaller", bigger: "Bigger", cancel: "Cancel", save: "Save",
        downloadBackgrounds: "Download backgrounds", scrapers: "Background scrapers", scrapersHelp: "Choose one source, search for the game, then select a background.", searchQuery: "Search query", search: "Search", searching: "Searching...", download: "Download",
        searchPlayStation: "Search PlayStation Store", searchingPlayStation: "Searching PlayStation Store...", choosePlayStationGame: "Choose the matching PlayStation game.", playStationGame: "PlayStation game", viewBackgrounds: "View backgrounds", loading: "Loading...", backToResults: "Back to results", readingBackgrounds: "Reading backgrounds for", chooseBackground: "Choose a PlayStation background.", noBackgrounds: "No suitable backgrounds found.", noPlayStationGames: "No PlayStation Store games found.",
        background: "Background", gameWallpaper: "Game wallpaper", enterSearchQuery: "Enter a search query.", searchFailed: "The search could not be completed.", gameTitleUnavailable: "Could not read the game title from Steam.", imagesFound: "Images found.", noImagesFound: "No images found.", imageDownloaded: "Launch image downloaded.", imageDownloadFailed: "Could not download the image.", chooseFileNotFolder: "Choose a file, not a folder.", imagePickerFailed: "Could not choose a launch image.", noGameSelected: "No game selected.",
        launchStarting: "Starting game...", launchCheckingLicense: "Checking license...", launchCheckingFiles: "Checking game files...", launchInstallingComponents: "Installing required components...", launchSyncingCloud: "Synchronizing Steam Cloud...", launchSyncingStats: "Synchronizing statistics...", launchSyncingController: "Loading controller configuration...", launchPreparing: "Preparing launch...", launchDelayed: "Launch delayed...", launchWaitingConfirmation: "Waiting for confirmation...", launchWaitingGame: "Waiting for the game...", launchUpdating: "Updating game..."
    },
    it: {
        soundbites: "Soundbites", soundbitesHelp: "Riproduce un breve jingle specifico del gioco mentre Launch Curtain è visibile.", soundbiteVolume: "Volume Soundbite", soundbiteMasterVolume: "Volume generale Soundbites", soundbiteMasterVolumeHelp: "Si applica sopra al volume individuale di ogni gioco senza modificarlo.", searchIidbSoundbites: "Cerca Soundbites su iiDB", searchingIidbSoundbites: "Ricerca Soundbites su iiDB...", noIidbSoundbites: "Nessun Soundbite iiDB trovato.", previewSoundbite: "Anteprima", stopSoundbitePreview: "Ferma anteprima", downloadApplySoundbite: "Scarica e applica", importSoundbite: "Importa Soundbite", removeSoundbite: "Rimuovi Soundbite", soundbiteLocal: "File locale", soundbiteIidb: "iiDB", soundbiteImported: "Soundbite locale importato.", soundbiteImportFailed: "Non è stato possibile importare il Soundbite.", soundbiteDownloadFailed: "Non è stato possibile scaricare il Soundbite.", playStationAssets: "Asset PlayStation", iidbAssets: "Asset iiDB", iidbSoundbites: "Soundbites iiDB", downloadIidbAssets: "Scarica Asset iiDB", removeIidbAssets: "Rimuovi Asset iiDB", downloadingIidbAssets: "Download Asset iiDB", removingIidbAssets: "Rimozione Asset iiDB", bulkSoundbites: "Scarica Soundbites iiDB mancanti", removeIidbSoundbites: "Rimuovi Soundbites iiDB", downloadingSoundbites: "Download Soundbites", removingSoundbites: "Rimozione Soundbites iiDB", showGamesWithoutSoundbites: "Mostra giochi senza Soundbites", hideGamesWithoutSoundbites: "Nascondi giochi senza Soundbites", showGamesWithSoundbites: "Mostra giochi con Soundbites", hideGamesWithSoundbites: "Nascondi giochi con Soundbites", manageSoundbiteExclusions: "Esclusioni assegnazione automatica Soundbites", soundbiteExclusionHelp: "I giochi esclusi vengono ignorati dall'assegnazione automatica dei Soundbites.", excluded: "Escluso", included: "Incluso", noGamesWithoutSoundbites: "Tutti i giochi della libreria hanno già un Soundbite oppure sono esclusi.", noGamesWithSoundbites: "Nessun gioco della libreria ha attualmente un Soundbite.", playStationAssetProtectionHelp: "Gli Asset PlayStation vengono applicati solo ai giochi installati senza una curtain esistente. Gli asset iiDB e quelli locali/manuali non vengono mai sostituiti.", iidbAssetProtectionHelp: "Gli Asset iiDB vengono applicati solo ai giochi senza una curtain esistente. Gli asset PlayStation e quelli manuali non vengono mai sostituiti.", bulkApplied: "Applicati", bulkSkipped: "Saltati", bulkFailed: "Non riusciti", bulkStop: "Ferma", bulkStopped: "Interrotto", iidb: "iiDB", assets: "Asset", yes: "Sì", no: "No", deleteUnusedSoundbites: "Elimina Soundbites non utilizzati", cleanupUnusedSoundbitesFailed: "Non è stato possibile eliminare i Soundbites non utilizzati.", confirmRemovePlayStationAssets: "Rimuovere tutti gli asset di lancio gestiti da PlayStation? Le immagini selezionate manualmente e gli asset iiDB verranno preservati.", confirmRemoveIidbAssets: "Rimuovere tutti gli asset di lancio gestiti da iiDB? Gli asset PlayStation e le immagini selezionate manualmente verranno preservati.", confirmRemoveIidbSoundbites: "Rimuovere tutti i Soundbites gestiti da iiDB attualmente assegnati ai giochi? I Soundbites locali verranno preservati.", confirmDeleteUnusedSoundbites: "Eliminare solo i file Soundbite iiDB che non sono più assegnati ad alcun gioco? I file locali/importati e i Soundbites attivi verranno preservati.", confirmDeleteUnusedImages: "Eliminare solo le immagini nella cartella gestita da Launch Curtain che non sono più utilizzate da alcun gioco?", whatToEdit: "Cosa vuoi modificare?", steamGridApiKey: "Chiave API SteamGridDB", steamGridApiHelp: "La ricerca Hero di SteamGridDB usa la tua chiave API personale. Launch Curtain non include alcuna chiave API.", steamGridApiPage: "Apri pagina API SteamGridDB", steamGridCredits: "Gli artwork Hero sono forniti tramite le API di SteamGridDB e rimangono contenuti di terze parti.", iisuCredits: "Un ringraziamento speciale al team e alla community di iiSU per aver creato iiDB e per l’incredibile lavoro dietro la sua collezione in continua crescita di artwork e Soundbites. La loro passione per la presentazione, la preservazione e la cura degli asset dei videogiochi ha reso possibile l’integrazione di iiDB in Launch Curtain. Un enorme grazie per aver costruito una risorsa così preziosa per la community videoludica e per aver reso questi asset accessibili a progetti come questo.", steamGridApiPlaceholder: "Incolla la tua chiave API personale", saveSteamGridApiKey: "Salva chiave API SteamGridDB", steamGridApiSaved: "Chiave API SteamGridDB salvata.", steamGridApiCleared: "Chiave API SteamGridDB rimossa.", steamGridApiSaveFailed: "Non è stato possibile salvare la chiave API SteamGridDB.", steamGridApiRequired: "Configura la tua chiave API personale di SteamGridDB nel QAM di Launch Curtain prima di effettuare la ricerca.", steamGridHeroOnlyHelp: "La ricerca SteamGridDB mostra esclusivamente artwork Hero.",
        maintenance: "Manutenzione", refreshGameCache: "Aggiorna cache giochi", deleteUnusedImages: "Elimina immagini inutilizzate", backup: "Backup", backupHelp: "Crea o ripristina un backup completo di impostazioni, curtain, Soundbites e file locali referenziati da Launch Curtain. Il backup include anche le impostazioni dei servizi salvate, come la chiave API SteamGridDB.", createBackup: "Crea backup", restoreBackup: "Ripristina backup", backupCreated: "Backup creato in", backupRestored: "Backup ripristinato correttamente.", backupFailed: "Non è stato possibile creare il backup.", restoreBackupFailed: "Non è stato possibile ripristinare il backup.", backupMissingFiles: "Alcuni file esterni non sono stati inclusi.", confirmRestoreBackup: "Ripristinare questo backup? Le impostazioni e i file gestiti attuali di Launch Curtain verranno sostituiti. Prima del ripristino viene creata automaticamente una copia temporanea di rollback.",
        downloadPlayStationAssetsInstalled: "Scarica asset PS dei giochi installati", noInstalledGames: "Nessun gioco Steam installato trovato.",
        downloadPlayStationAssets: "Scarica asset PlayStation", removePlayStationAssets: "Rimuovi asset PlayStation", downloadingPlayStationAssets: "Download asset PlayStation", removingPlayStationAssets: "Rimozione asset PlayStation", playStationBulkApplied: "Applicati", playStationBulkRemoved: "Rimossi", playStationBulkSkipped: "Saltati", playStationBulkFailed: "Non riusciti", playStationBulkError: "Non è stato possibile completare l'operazione PlayStation",
        tabGame: "Gioco", tabAppearance: "Aspetto", tabScrapers: "Scraper",
        gameBehavior: "Comportamento di Launch Curtain", gameBehaviorHelp: "Scegli come deve comportarsi Launch Curtain con questo gioco.", enableForGame: "Attiva Launch Curtain per questo gioco",
        logoHelp: "Gestisci il logo del gioco e apri l'editor visuale.", showLogo: "Mostra logo", openEditor: "Apri Editor", logoZoom: "Attiva animazione zoom-in del logo", bgZoom: "Attiva animazione zoom-out dello sfondo",
        launchImage: "Immagine di lancio", noLaunchImage: "Nessuna immagine di lancio selezionata", chooseLaunchImage: "Scegli immagine di lancio a schermo intero", clearLaunchImage: "Rimuovi immagine di lancio",
        editorTitle: "Editor", close: "Chiudi", saving: "Salvataggio...", editorSaveFailed: "Non è stato possibile salvare le impostazioni dell'editor.", backgroundOpacity: "Opacità dello sfondo", logoShadowOpacity: "Opacità ombra del logo", logoShadowBlur: "Blur ombra del logo", up: "Su", down: "Giù", left: "Sinistra", right: "Destra", reset: "Ripristina", smaller: "Più piccolo", bigger: "Più grande", cancel: "Annulla", save: "Salva",
        downloadBackgrounds: "Download sfondi", scrapers: "Scraper degli sfondi", scrapersHelp: "Scegli una sorgente, cerca il gioco e poi seleziona uno sfondo.", searchQuery: "Testo da cercare", search: "Cerca", searching: "Ricerca in corso...", download: "Scarica",
        searchPlayStation: "Cerca nel PlayStation Store", searchingPlayStation: "Ricerca nel PlayStation Store...", choosePlayStationGame: "Scegli il gioco PlayStation corretto.", playStationGame: "Gioco PlayStation", viewBackgrounds: "Vedi sfondi", loading: "Caricamento...", backToResults: "Torna ai risultati", readingBackgrounds: "Lettura degli sfondi per", chooseBackground: "Scegli uno sfondo PlayStation.", noBackgrounds: "Nessuno sfondo adatto trovato.", noPlayStationGames: "Nessun gioco trovato nel PlayStation Store.",
        background: "Sfondo", gameWallpaper: "Sfondo del gioco", enterSearchQuery: "Inserisci un testo da cercare.", searchFailed: "Non è stato possibile completare la ricerca.", gameTitleUnavailable: "Non è stato possibile leggere il titolo del gioco da Steam.", imagesFound: "Immagini trovate.", noImagesFound: "Nessuna immagine trovata.", imageDownloaded: "Immagine di lancio scaricata.", imageDownloadFailed: "Non è stato possibile scaricare l'immagine.", chooseFileNotFolder: "Scegli un file, non una cartella.", imagePickerFailed: "Non è stato possibile scegliere l'immagine di lancio.", noGameSelected: "Nessun gioco selezionato.",
        launchStarting: "Avvio del gioco...", launchCheckingLicense: "Verifica della licenza...", launchCheckingFiles: "Verifica dei file di gioco...", launchInstallingComponents: "Installazione dei componenti necessari...", launchSyncingCloud: "Sincronizzazione di Steam Cloud...", launchSyncingStats: "Sincronizzazione delle statistiche...", launchSyncingController: "Caricamento della configurazione controller...", launchPreparing: "Preparazione dell'avvio...", launchDelayed: "Avvio ritardato...", launchWaitingConfirmation: "In attesa di conferma...", launchWaitingGame: "In attesa del gioco...", launchUpdating: "Aggiornamento del gioco..."
    }
};

const EXTRA_TRANSLATIONS = {
    fr: {
        timeoutEnabled: "Activer le délai d'expiration", modeAuto: "Automatique", forceMode: "Forcer le mode", gameTimeout: "Délai du jeu", gameTimeoutSeconds: "Délai du jeu (secondes)", timeoutHelp: "Masque automatiquement le rideau lorsque le délai expire.", timeoutDisabledHelp: "Le rideau reste affiché jusqu'à la détection du jeu.", exitDelay: "Délai de sortie", exitDelayHelp: "Maintient le rideau visible un peu plus longtemps après la détection du jeu.",
        maintenance: "Maintenance", refreshGameCache: "Actualiser le cache des jeux", deleteUnusedImages: "Supprimer les images inutilisées",
        downloadPlayStationAssetsInstalled: "Télécharger les ressources PS des jeux installés", noInstalledGames: "Aucun jeu Steam installé n'a été trouvé.",
        downloadPlayStationAssets: "Télécharger les ressources PlayStation", removePlayStationAssets: "Supprimer les ressources PlayStation", downloadingPlayStationAssets: "Téléchargement des ressources PlayStation", removingPlayStationAssets: "Suppression des ressources PlayStation", playStationBulkApplied: "Appliquées", playStationBulkRemoved: "Supprimées", playStationBulkSkipped: "Ignorées", playStationBulkFailed: "Échecs", playStationBulkError: "L'opération groupée PlayStation n'a pas pu être terminée",
        tabGame: "Jeu", tabAppearance: "Apparence", tabScrapers: "Sources", gameBehavior: "Comportement de Launch Curtain", gameBehaviorHelp: "Choisissez le comportement de Launch Curtain pour ce jeu.", enableForGame: "Activer Launch Curtain pour ce jeu",
        logoHelp: "Gérez le logo du jeu et ouvrez l'éditeur visuel.", showLogo: "Afficher le logo", openEditor: "Ouvrir l'éditeur", logoZoom: "Activer l'animation de zoom avant du logo", bgZoom: "Activer l'animation de zoom arrière de l'arrière-plan",
        launchImage: "Image de lancement", noLaunchImage: "Aucune image de lancement sélectionnée", chooseLaunchImage: "Choisir une image de lancement plein écran", clearLaunchImage: "Supprimer l'image de lancement",
        editorTitle: "Éditeur", close: "Fermer", saving: "Enregistrement...", editorSaveFailed: "Impossible d'enregistrer les paramètres de l'éditeur.", backgroundOpacity: "Opacité de l'arrière-plan", logoShadowOpacity: "Opacité de l'ombre du logo", logoShadowBlur: "Flou de l'ombre du logo", up: "Haut", down: "Bas", left: "Gauche", right: "Droite", reset: "Réinitialiser", smaller: "Réduire", bigger: "Agrandir", cancel: "Annuler", save: "Enregistrer",
        downloadBackgrounds: "Télécharger des arrière-plans", scrapers: "Sources d'arrière-plans", scrapersHelp: "Choisissez une source, recherchez le jeu, puis sélectionnez un arrière-plan.", searchQuery: "Texte à rechercher", search: "Rechercher", searching: "Recherche...", download: "Télécharger",
        searchPlayStation: "Rechercher sur le PlayStation Store", searchingPlayStation: "Recherche sur le PlayStation Store...", choosePlayStationGame: "Choisissez le jeu PlayStation correspondant.", playStationGame: "Jeu PlayStation", viewBackgrounds: "Voir les arrière-plans", loading: "Chargement...", backToResults: "Retour aux résultats", readingBackgrounds: "Lecture des arrière-plans pour", chooseBackground: "Choisissez un arrière-plan PlayStation.", noBackgrounds: "Aucun arrière-plan adapté trouvé.", noPlayStationGames: "Aucun jeu trouvé sur le PlayStation Store.",
        background: "Arrière-plan", gameWallpaper: "Fond d'écran du jeu", enterSearchQuery: "Saisissez un texte à rechercher.", searchFailed: "La recherche n'a pas pu être terminée.", gameTitleUnavailable: "Impossible de lire le titre du jeu depuis Steam.", imagesFound: "Images trouvées.", noImagesFound: "Aucune image trouvée.", imageDownloaded: "Image de lancement téléchargée.", imageDownloadFailed: "Impossible de télécharger l'image.", chooseFileNotFolder: "Choisissez un fichier, pas un dossier.", imagePickerFailed: "Impossible de choisir l'image de lancement.", noGameSelected: "Aucun jeu sélectionné.",
        launchStarting: "Démarrage du jeu...", launchCheckingLicense: "Vérification de la licence...", launchCheckingFiles: "Vérification des fichiers du jeu...", launchInstallingComponents: "Installation des composants requis...", launchSyncingCloud: "Synchronisation de Steam Cloud...", launchSyncingStats: "Synchronisation des statistiques...", launchSyncingController: "Chargement de la configuration de la manette...", launchPreparing: "Préparation du lancement...", launchDelayed: "Lancement retardé...", launchWaitingConfirmation: "En attente de confirmation...", launchWaitingGame: "En attente du jeu...", launchUpdating: "Mise à jour du jeu..."
    },
    es: {
        timeoutEnabled: "Activar tiempo de espera", modeAuto: "Automático", forceMode: "Forzar modo", gameTimeout: "Tiempo de espera del juego", gameTimeoutSeconds: "Tiempo de espera del juego (segundos)", timeoutHelp: "Oculta automáticamente la cortina cuando se agota el tiempo.", timeoutDisabledHelp: "La cortina permanece visible hasta que se detecta el juego.", exitDelay: "Retraso de salida", exitDelayHelp: "Mantiene la cortina visible un poco más después de detectar el juego.",
        maintenance: "Mantenimiento", refreshGameCache: "Actualizar caché de juegos", deleteUnusedImages: "Eliminar imágenes sin usar", downloadPlayStationAssetsInstalled: "Descargar recursos de PS para juegos instalados", noInstalledGames: "No se encontraron juegos de Steam instalados.", downloadPlayStationAssets: "Descargar recursos de PlayStation", removePlayStationAssets: "Eliminar recursos de PlayStation", downloadingPlayStationAssets: "Descargando recursos de PlayStation", removingPlayStationAssets: "Eliminando recursos de PlayStation", playStationBulkApplied: "Aplicados", playStationBulkRemoved: "Eliminados", playStationBulkSkipped: "Omitidos", playStationBulkFailed: "Fallidos", playStationBulkError: "No se pudo completar la operación por lotes de PlayStation",
        tabGame: "Juego", tabAppearance: "Apariencia", tabScrapers: "Fuentes", gameBehavior: "Comportamiento de Launch Curtain", gameBehaviorHelp: "Elige cómo se comportará Launch Curtain con este juego.", enableForGame: "Activar Launch Curtain para este juego", logoHelp: "Controla el logotipo del juego y abre el editor visual.", showLogo: "Mostrar logotipo", openEditor: "Abrir editor", logoZoom: "Activar animación de acercamiento del logotipo", bgZoom: "Activar animación de alejamiento del fondo",
        launchImage: "Imagen de inicio", noLaunchImage: "No hay ninguna imagen de inicio seleccionada", chooseLaunchImage: "Elegir imagen de inicio a pantalla completa", clearLaunchImage: "Quitar imagen de inicio", editorTitle: "Editor", close: "Cerrar", saving: "Guardando...", editorSaveFailed: "No se pudieron guardar los ajustes del editor.", backgroundOpacity: "Opacidad del fondo", logoShadowOpacity: "Opacidad de la sombra del logotipo", logoShadowBlur: "Desenfoque de la sombra del logotipo", up: "Arriba", down: "Abajo", left: "Izquierda", right: "Derecha", reset: "Restablecer", smaller: "Más pequeño", bigger: "Más grande", cancel: "Cancelar", save: "Guardar",
        downloadBackgrounds: "Descargar fondos", scrapers: "Fuentes de fondos", scrapersHelp: "Elige una fuente, busca el juego y selecciona un fondo.", searchQuery: "Texto de búsqueda", search: "Buscar", searching: "Buscando...", download: "Descargar", searchPlayStation: "Buscar en PlayStation Store", searchingPlayStation: "Buscando en PlayStation Store...", choosePlayStationGame: "Elige el juego de PlayStation correspondiente.", playStationGame: "Juego de PlayStation", viewBackgrounds: "Ver fondos", loading: "Cargando...", backToResults: "Volver a los resultados", readingBackgrounds: "Leyendo fondos para", chooseBackground: "Elige un fondo de PlayStation.", noBackgrounds: "No se encontraron fondos adecuados.", noPlayStationGames: "No se encontraron juegos en PlayStation Store.",
        background: "Fondo", gameWallpaper: "Fondo del juego", enterSearchQuery: "Introduce un texto de búsqueda.", searchFailed: "No se pudo completar la búsqueda.", gameTitleUnavailable: "No se pudo leer el título del juego desde Steam.", imagesFound: "Imágenes encontradas.", noImagesFound: "No se encontraron imágenes.", imageDownloaded: "Imagen de inicio descargada.", imageDownloadFailed: "No se pudo descargar la imagen.", chooseFileNotFolder: "Elige un archivo, no una carpeta.", imagePickerFailed: "No se pudo elegir la imagen de inicio.", noGameSelected: "No hay ningún juego seleccionado.", launchStarting: "Iniciando juego...", launchCheckingLicense: "Comprobando licencia...", launchCheckingFiles: "Comprobando archivos del juego...", launchInstallingComponents: "Instalando componentes necesarios...", launchSyncingCloud: "Sincronizando Steam Cloud...", launchSyncingStats: "Sincronizando estadísticas...", launchSyncingController: "Cargando configuración del mando...", launchPreparing: "Preparando el inicio...", launchDelayed: "Inicio retrasado...", launchWaitingConfirmation: "Esperando confirmación...", launchWaitingGame: "Esperando al juego...", launchUpdating: "Actualizando juego..."
    },
    de: {
        timeoutEnabled: "Zeitlimit aktivieren", modeAuto: "Automatisch", forceMode: "Modus erzwingen", gameTimeout: "Spiel-Zeitlimit", gameTimeoutSeconds: "Spiel-Zeitlimit (Sekunden)", timeoutHelp: "Blendet den Vorhang nach Ablauf des Zeitlimits automatisch aus.", timeoutDisabledHelp: "Der Vorhang bleibt sichtbar, bis das Spiel erkannt wird.", exitDelay: "Ausblendverzögerung", exitDelayHelp: "Lässt den Vorhang nach der Spielerkennung etwas länger sichtbar.",
        maintenance: "Wartung", refreshGameCache: "Spiele-Cache aktualisieren", deleteUnusedImages: "Ungenutzte Bilder löschen", downloadPlayStationAssetsInstalled: "PS-Assets für installierte Spiele laden", noInstalledGames: "Keine installierten Steam-Spiele gefunden.", downloadPlayStationAssets: "PlayStation-Assets herunterladen", removePlayStationAssets: "PlayStation-Assets entfernen", downloadingPlayStationAssets: "PlayStation-Assets werden heruntergeladen", removingPlayStationAssets: "PlayStation-Assets werden entfernt", playStationBulkApplied: "Angewendet", playStationBulkRemoved: "Entfernt", playStationBulkSkipped: "Übersprungen", playStationBulkFailed: "Fehlgeschlagen", playStationBulkError: "Der PlayStation-Sammelvorgang konnte nicht abgeschlossen werden",
        tabGame: "Spiel", tabAppearance: "Darstellung", tabScrapers: "Quellen", gameBehavior: "Verhalten von Launch Curtain", gameBehaviorHelp: "Lege fest, wie sich Launch Curtain bei diesem Spiel verhält.", enableForGame: "Launch Curtain für dieses Spiel aktivieren", logoHelp: "Verwalte das Spiellogo und öffne den visuellen Editor.", showLogo: "Logo anzeigen", openEditor: "Editor öffnen", logoZoom: "Einzoom-Animation des Logos aktivieren", bgZoom: "Auszoom-Animation des Hintergrunds aktivieren",
        launchImage: "Startbild", noLaunchImage: "Kein Startbild ausgewählt", chooseLaunchImage: "Vollbild-Startbild auswählen", clearLaunchImage: "Startbild entfernen", editorTitle: "Editor", close: "Schließen", saving: "Speichern...", editorSaveFailed: "Die Editor-Einstellungen konnten nicht gespeichert werden.", backgroundOpacity: "Hintergrunddeckkraft", logoShadowOpacity: "Deckkraft des Logoschattens", logoShadowBlur: "Unschärfe des Logoschattens", up: "Oben", down: "Unten", left: "Links", right: "Rechts", reset: "Zurücksetzen", smaller: "Kleiner", bigger: "Größer", cancel: "Abbrechen", save: "Speichern",
        downloadBackgrounds: "Hintergründe herunterladen", scrapers: "Hintergrundquellen", scrapersHelp: "Wähle eine Quelle, suche nach dem Spiel und wähle anschließend einen Hintergrund.", searchQuery: "Suchbegriff", search: "Suchen", searching: "Suche...", download: "Herunterladen", searchPlayStation: "Im PlayStation Store suchen", searchingPlayStation: "PlayStation Store wird durchsucht...", choosePlayStationGame: "Wähle das passende PlayStation-Spiel.", playStationGame: "PlayStation-Spiel", viewBackgrounds: "Hintergründe anzeigen", loading: "Laden...", backToResults: "Zurück zu den Ergebnissen", readingBackgrounds: "Hintergründe werden gelesen für", chooseBackground: "Wähle einen PlayStation-Hintergrund.", noBackgrounds: "Keine passenden Hintergründe gefunden.", noPlayStationGames: "Keine Spiele im PlayStation Store gefunden.",
        background: "Hintergrund", gameWallpaper: "Spielhintergrund", enterSearchQuery: "Gib einen Suchbegriff ein.", searchFailed: "Die Suche konnte nicht abgeschlossen werden.", gameTitleUnavailable: "Der Spieltitel konnte nicht aus Steam gelesen werden.", imagesFound: "Bilder gefunden.", noImagesFound: "Keine Bilder gefunden.", imageDownloaded: "Startbild heruntergeladen.", imageDownloadFailed: "Das Bild konnte nicht heruntergeladen werden.", chooseFileNotFolder: "Wähle eine Datei, keinen Ordner.", imagePickerFailed: "Das Startbild konnte nicht ausgewählt werden.", noGameSelected: "Kein Spiel ausgewählt.", launchStarting: "Spiel wird gestartet...", launchCheckingLicense: "Lizenz wird geprüft...", launchCheckingFiles: "Spieldateien werden geprüft...", launchInstallingComponents: "Erforderliche Komponenten werden installiert...", launchSyncingCloud: "Steam Cloud wird synchronisiert...", launchSyncingStats: "Statistiken werden synchronisiert...", launchSyncingController: "Controller-Konfiguration wird geladen...", launchPreparing: "Start wird vorbereitet...", launchDelayed: "Start verzögert...", launchWaitingConfirmation: "Warten auf Bestätigung...", launchWaitingGame: "Warten auf das Spiel...", launchUpdating: "Spiel wird aktualisiert..."
    },
    pt: {
        timeoutEnabled: "Ativar tempo limite", modeAuto: "Automático", forceMode: "Forçar modo", gameTimeout: "Tempo limite do jogo", gameTimeoutSeconds: "Tempo limite do jogo (segundos)", timeoutHelp: "Oculta automaticamente a cortina quando o tempo limite termina.", timeoutDisabledHelp: "A cortina permanece visível até o jogo ser detetado.", exitDelay: "Atraso de saída", exitDelayHelp: "Mantém a cortina visível por mais algum tempo depois de detetar o jogo.",
        maintenance: "Manutenção", refreshGameCache: "Atualizar cache de jogos", deleteUnusedImages: "Eliminar imagens não utilizadas", downloadPlayStationAssetsInstalled: "Transferir recursos PS dos jogos instalados", noInstalledGames: "Não foram encontrados jogos Steam instalados.", downloadPlayStationAssets: "Transferir recursos PlayStation", removePlayStationAssets: "Remover recursos PlayStation", downloadingPlayStationAssets: "A transferir recursos PlayStation", removingPlayStationAssets: "A remover recursos PlayStation", playStationBulkApplied: "Aplicados", playStationBulkRemoved: "Removidos", playStationBulkSkipped: "Ignorados", playStationBulkFailed: "Falharam", playStationBulkError: "Não foi possível concluir a operação em lote da PlayStation",
        tabGame: "Jogo", tabAppearance: "Aspeto", tabScrapers: "Fontes", gameBehavior: "Comportamento do Launch Curtain", gameBehaviorHelp: "Escolha como o Launch Curtain se comporta neste jogo.", enableForGame: "Ativar Launch Curtain neste jogo", logoHelp: "Controle o logótipo do jogo e abra o editor visual.", showLogo: "Mostrar logótipo", openEditor: "Abrir editor", logoZoom: "Ativar animação de aproximação do logótipo", bgZoom: "Ativar animação de afastamento do fundo",
        launchImage: "Imagem de arranque", noLaunchImage: "Nenhuma imagem de arranque selecionada", chooseLaunchImage: "Escolher imagem de arranque em ecrã inteiro", clearLaunchImage: "Remover imagem de arranque", editorTitle: "Editor", close: "Fechar", saving: "A guardar...", editorSaveFailed: "Não foi possível guardar as definições do editor.", backgroundOpacity: "Opacidade do fundo", logoShadowOpacity: "Opacidade da sombra do logótipo", logoShadowBlur: "Desfoque da sombra do logótipo", up: "Cima", down: "Baixo", left: "Esquerda", right: "Direita", reset: "Repor", smaller: "Menor", bigger: "Maior", cancel: "Cancelar", save: "Guardar",
        downloadBackgrounds: "Transferir fundos", scrapers: "Fontes de fundos", scrapersHelp: "Escolha uma fonte, procure o jogo e selecione um fundo.", searchQuery: "Texto de pesquisa", search: "Pesquisar", searching: "A pesquisar...", download: "Transferir", searchPlayStation: "Pesquisar na PlayStation Store", searchingPlayStation: "A pesquisar na PlayStation Store...", choosePlayStationGame: "Escolha o jogo PlayStation correspondente.", playStationGame: "Jogo PlayStation", viewBackgrounds: "Ver fundos", loading: "A carregar...", backToResults: "Voltar aos resultados", readingBackgrounds: "A ler fundos para", chooseBackground: "Escolha um fundo PlayStation.", noBackgrounds: "Não foram encontrados fundos adequados.", noPlayStationGames: "Não foram encontrados jogos na PlayStation Store.",
        background: "Fundo", gameWallpaper: "Fundo do jogo", enterSearchQuery: "Introduza um texto de pesquisa.", searchFailed: "Não foi possível concluir a pesquisa.", gameTitleUnavailable: "Não foi possível ler o título do jogo no Steam.", imagesFound: "Imagens encontradas.", noImagesFound: "Nenhuma imagem encontrada.", imageDownloaded: "Imagem de arranque transferida.", imageDownloadFailed: "Não foi possível transferir a imagem.", chooseFileNotFolder: "Escolha um ficheiro, não uma pasta.", imagePickerFailed: "Não foi possível escolher a imagem de arranque.", noGameSelected: "Nenhum jogo selecionado.", launchStarting: "A iniciar o jogo...", launchCheckingLicense: "A verificar a licença...", launchCheckingFiles: "A verificar os ficheiros do jogo...", launchInstallingComponents: "A instalar os componentes necessários...", launchSyncingCloud: "A sincronizar o Steam Cloud...", launchSyncingStats: "A sincronizar estatísticas...", launchSyncingController: "A carregar a configuração do comando...", launchPreparing: "A preparar o arranque...", launchDelayed: "Arranque atrasado...", launchWaitingConfirmation: "A aguardar confirmação...", launchWaitingGame: "A aguardar o jogo...", launchUpdating: "A atualizar o jogo..."
    },
    "pt-br": {
        timeoutEnabled: "Ativar tempo limite", modeAuto: "Automático", forceMode: "Forçar modo", gameTimeout: "Tempo limite do jogo", gameTimeoutSeconds: "Tempo limite do jogo (segundos)", timeoutHelp: "Oculta automaticamente a cortina quando o tempo limite termina.", timeoutDisabledHelp: "A cortina permanece visível até o jogo ser detectado.", exitDelay: "Atraso de saída", exitDelayHelp: "Mantém a cortina visível por mais algum tempo depois de detectar o jogo.",
        maintenance: "Manutenção", refreshGameCache: "Atualizar cache de jogos", deleteUnusedImages: "Excluir imagens não utilizadas", downloadPlayStationAssetsInstalled: "Baixar recursos PS dos jogos instalados", noInstalledGames: "Nenhum jogo Steam instalado foi encontrado.", downloadPlayStationAssets: "Baixar recursos do PlayStation", removePlayStationAssets: "Remover recursos do PlayStation", downloadingPlayStationAssets: "Baixando recursos do PlayStation", removingPlayStationAssets: "Removendo recursos do PlayStation", playStationBulkApplied: "Aplicados", playStationBulkRemoved: "Removidos", playStationBulkSkipped: "Ignorados", playStationBulkFailed: "Falharam", playStationBulkError: "Não foi possível concluir a operação em lote do PlayStation",
        tabGame: "Jogo", tabAppearance: "Aparência", tabScrapers: "Fontes", gameBehavior: "Comportamento do Launch Curtain", gameBehaviorHelp: "Escolha como o Launch Curtain se comporta neste jogo.", enableForGame: "Ativar Launch Curtain neste jogo", logoHelp: "Controle o logotipo do jogo e abra o editor visual.", showLogo: "Mostrar logotipo", openEditor: "Abrir editor", logoZoom: "Ativar animação de aproximação do logotipo", bgZoom: "Ativar animação de afastamento do fundo",
        launchImage: "Imagem de inicialização", noLaunchImage: "Nenhuma imagem de inicialização selecionada", chooseLaunchImage: "Escolher imagem de inicialização em tela cheia", clearLaunchImage: "Remover imagem de inicialização", editorTitle: "Editor", close: "Fechar", saving: "Salvando...", editorSaveFailed: "Não foi possível salvar as configurações do editor.", backgroundOpacity: "Opacidade do fundo", logoShadowOpacity: "Opacidade da sombra do logotipo", logoShadowBlur: "Desfoque da sombra do logotipo", up: "Cima", down: "Baixo", left: "Esquerda", right: "Direita", reset: "Redefinir", smaller: "Menor", bigger: "Maior", cancel: "Cancelar", save: "Salvar",
        downloadBackgrounds: "Baixar fundos", scrapers: "Fontes de fundos", scrapersHelp: "Escolha uma fonte, pesquise o jogo e selecione um fundo.", searchQuery: "Texto de pesquisa", search: "Pesquisar", searching: "Pesquisando...", download: "Baixar", searchPlayStation: "Pesquisar na PlayStation Store", searchingPlayStation: "Pesquisando na PlayStation Store...", choosePlayStationGame: "Escolha o jogo PlayStation correspondente.", playStationGame: "Jogo PlayStation", viewBackgrounds: "Ver fundos", loading: "Carregando...", backToResults: "Voltar aos resultados", readingBackgrounds: "Lendo fundos para", chooseBackground: "Escolha um fundo do PlayStation.", noBackgrounds: "Nenhum fundo adequado encontrado.", noPlayStationGames: "Nenhum jogo encontrado na PlayStation Store.",
        background: "Fundo", gameWallpaper: "Papel de parede do jogo", enterSearchQuery: "Digite um texto de pesquisa.", searchFailed: "Não foi possível concluir a pesquisa.", gameTitleUnavailable: "Não foi possível ler o título do jogo no Steam.", imagesFound: "Imagens encontradas.", noImagesFound: "Nenhuma imagem encontrada.", imageDownloaded: "Imagem de inicialização baixada.", imageDownloadFailed: "Não foi possível baixar a imagem.", chooseFileNotFolder: "Escolha um arquivo, não uma pasta.", imagePickerFailed: "Não foi possível escolher a imagem de inicialização.", noGameSelected: "Nenhum jogo selecionado.", launchStarting: "Iniciando o jogo...", launchCheckingLicense: "Verificando a licença...", launchCheckingFiles: "Verificando os arquivos do jogo...", launchInstallingComponents: "Instalando os componentes necessários...", launchSyncingCloud: "Sincronizando o Steam Cloud...", launchSyncingStats: "Sincronizando estatísticas...", launchSyncingController: "Carregando a configuração do controle...", launchPreparing: "Preparando a inicialização...", launchDelayed: "Inicialização atrasada...", launchWaitingConfirmation: "Aguardando confirmação...", launchWaitingGame: "Aguardando o jogo...", launchUpdating: "Atualizando o jogo..."
    },
    nl: {
        timeoutEnabled: "Time-out inschakelen", modeAuto: "Automatisch", forceMode: "Modus forceren", gameTimeout: "Time-out voor spel", gameTimeoutSeconds: "Time-out voor spel (seconden)", timeoutHelp: "Verbergt het gordijn automatisch wanneer de time-out verloopt.", timeoutDisabledHelp: "Het gordijn blijft zichtbaar totdat het spel is gedetecteerd.", exitDelay: "Afsluitvertraging", exitDelayHelp: "Houdt het gordijn iets langer zichtbaar nadat het spel is gedetecteerd.",
        maintenance: "Onderhoud", refreshGameCache: "Spelcache vernieuwen", deleteUnusedImages: "Ongebruikte afbeeldingen verwijderen", downloadPlayStationAssetsInstalled: "PS-assets voor geïnstalleerde spellen downloaden", noInstalledGames: "Er zijn geen geïnstalleerde Steam-spellen gevonden.", downloadPlayStationAssets: "PlayStation-assets downloaden", removePlayStationAssets: "PlayStation-assets verwijderen", downloadingPlayStationAssets: "PlayStation-assets downloaden", removingPlayStationAssets: "PlayStation-assets verwijderen", playStationBulkApplied: "Toegepast", playStationBulkRemoved: "Verwijderd", playStationBulkSkipped: "Overgeslagen", playStationBulkFailed: "Mislukt", playStationBulkError: "De PlayStation-bulkbewerking kon niet worden voltooid",
        tabGame: "Spel", tabAppearance: "Uiterlijk", tabScrapers: "Bronnen", gameBehavior: "Gedrag van Launch Curtain", gameBehaviorHelp: "Kies hoe Launch Curtain zich voor dit spel gedraagt.", enableForGame: "Launch Curtain inschakelen voor dit spel", logoHelp: "Beheer het spellogo en open de visuele editor.", showLogo: "Logo tonen", openEditor: "Editor openen", logoZoom: "Inzoomanimatie van logo inschakelen", bgZoom: "Uitzoomanimatie van achtergrond inschakelen",
        launchImage: "Startafbeelding", noLaunchImage: "Geen startafbeelding geselecteerd", chooseLaunchImage: "Startafbeelding op volledig scherm kiezen", clearLaunchImage: "Startafbeelding verwijderen", editorTitle: "Editor", close: "Sluiten", saving: "Opslaan...", editorSaveFailed: "De editorinstellingen konden niet worden opgeslagen.", backgroundOpacity: "Dekking van achtergrond", logoShadowOpacity: "Dekking van logoschaduw", logoShadowBlur: "Vervaging van logoschaduw", up: "Omhoog", down: "Omlaag", left: "Links", right: "Rechts", reset: "Herstellen", smaller: "Kleiner", bigger: "Groter", cancel: "Annuleren", save: "Opslaan",
        downloadBackgrounds: "Achtergronden downloaden", scrapers: "Achtergrondbronnen", scrapersHelp: "Kies een bron, zoek het spel en selecteer daarna een achtergrond.", searchQuery: "Zoekterm", search: "Zoeken", searching: "Zoeken...", download: "Downloaden", searchPlayStation: "Zoeken in PlayStation Store", searchingPlayStation: "Zoeken in PlayStation Store...", choosePlayStationGame: "Kies het overeenkomende PlayStation-spel.", playStationGame: "PlayStation-spel", viewBackgrounds: "Achtergronden bekijken", loading: "Laden...", backToResults: "Terug naar resultaten", readingBackgrounds: "Achtergronden lezen voor", chooseBackground: "Kies een PlayStation-achtergrond.", noBackgrounds: "Geen geschikte achtergronden gevonden.", noPlayStationGames: "Geen spellen gevonden in PlayStation Store.",
        background: "Achtergrond", gameWallpaper: "Spelachtergrond", enterSearchQuery: "Voer een zoekterm in.", searchFailed: "De zoekopdracht kon niet worden voltooid.", gameTitleUnavailable: "De speltitel kon niet uit Steam worden gelezen.", imagesFound: "Afbeeldingen gevonden.", noImagesFound: "Geen afbeeldingen gevonden.", imageDownloaded: "Startafbeelding gedownload.", imageDownloadFailed: "De afbeelding kon niet worden gedownload.", chooseFileNotFolder: "Kies een bestand, geen map.", imagePickerFailed: "De startafbeelding kon niet worden gekozen.", noGameSelected: "Geen spel geselecteerd.", launchStarting: "Spel starten...", launchCheckingLicense: "Licentie controleren...", launchCheckingFiles: "Spelbestanden controleren...", launchInstallingComponents: "Vereiste onderdelen installeren...", launchSyncingCloud: "Steam Cloud synchroniseren...", launchSyncingStats: "Statistieken synchroniseren...", launchSyncingController: "Controllerconfiguratie laden...", launchPreparing: "Start voorbereiden...", launchDelayed: "Start vertraagd...", launchWaitingConfirmation: "Wachten op bevestiging...", launchWaitingGame: "Wachten op het spel...", launchUpdating: "Spel bijwerken..."
    },
    uk: {
        timeoutEnabled: "Увімкнути тайм-аут", modeAuto: "Автоматично", forceMode: "Примусовий режим", gameTimeout: "Тайм-аут гри", gameTimeoutSeconds: "Тайм-аут гри (секунди)", timeoutHelp: "Автоматично приховує завісу після завершення тайм-ауту.", timeoutDisabledHelp: "Завіса залишається видимою, доки гру не буде виявлено.", exitDelay: "Затримка виходу", exitDelayHelp: "Залишає завісу видимою трохи довше після виявлення гри.",
        maintenance: "Обслуговування", refreshGameCache: "Оновити кеш ігор", deleteUnusedImages: "Видалити невикористані зображення", downloadPlayStationAssetsInstalled: "Завантажити ресурси PS для встановлених ігор", noInstalledGames: "Не знайдено встановлених ігор Steam.", downloadPlayStationAssets: "Завантажити ресурси PlayStation", removePlayStationAssets: "Видалити ресурси PlayStation", downloadingPlayStationAssets: "Завантаження ресурсів PlayStation", removingPlayStationAssets: "Видалення ресурсів PlayStation", playStationBulkApplied: "Застосовано", playStationBulkRemoved: "Видалено", playStationBulkSkipped: "Пропущено", playStationBulkFailed: "Помилки", playStationBulkError: "Не вдалося завершити групову операцію PlayStation",
        tabGame: "Гра", tabAppearance: "Вигляд", tabScrapers: "Джерела", gameBehavior: "Поведінка Launch Curtain", gameBehaviorHelp: "Виберіть поведінку Launch Curtain для цієї гри.", enableForGame: "Увімкнути Launch Curtain для цієї гри", logoHelp: "Керуйте логотипом гри та відкрийте візуальний редактор.", showLogo: "Показувати логотип", openEditor: "Відкрити редактор", logoZoom: "Увімкнути анімацію наближення логотипу", bgZoom: "Увімкнути анімацію віддалення фону",
        launchImage: "Зображення запуску", noLaunchImage: "Зображення запуску не вибрано", chooseLaunchImage: "Вибрати повноекранне зображення запуску", clearLaunchImage: "Видалити зображення запуску", editorTitle: "Редактор", close: "Закрити", saving: "Збереження...", editorSaveFailed: "Не вдалося зберегти налаштування редактора.", backgroundOpacity: "Непрозорість фону", logoShadowOpacity: "Непрозорість тіні логотипу", logoShadowBlur: "Розмиття тіні логотипу", up: "Вгору", down: "Вниз", left: "Ліворуч", right: "Праворуч", reset: "Скинути", smaller: "Менше", bigger: "Більше", cancel: "Скасувати", save: "Зберегти",
        downloadBackgrounds: "Завантажити фони", scrapers: "Джерела фонів", scrapersHelp: "Виберіть джерело, знайдіть гру, а потім виберіть фон.", searchQuery: "Пошуковий запит", search: "Пошук", searching: "Пошук...", download: "Завантажити", searchPlayStation: "Пошук у PlayStation Store", searchingPlayStation: "Пошук у PlayStation Store...", choosePlayStationGame: "Виберіть відповідну гру PlayStation.", playStationGame: "Гра PlayStation", viewBackgrounds: "Переглянути фони", loading: "Завантаження...", backToResults: "Назад до результатів", readingBackgrounds: "Читання фонів для", chooseBackground: "Виберіть фон PlayStation.", noBackgrounds: "Відповідних фонів не знайдено.", noPlayStationGames: "Ігор у PlayStation Store не знайдено.",
        background: "Фон", gameWallpaper: "Шпалери гри", enterSearchQuery: "Введіть пошуковий запит.", searchFailed: "Не вдалося завершити пошук.", gameTitleUnavailable: "Не вдалося прочитати назву гри зі Steam.", imagesFound: "Зображення знайдено.", noImagesFound: "Зображень не знайдено.", imageDownloaded: "Зображення запуску завантажено.", imageDownloadFailed: "Не вдалося завантажити зображення.", chooseFileNotFolder: "Виберіть файл, а не папку.", imagePickerFailed: "Не вдалося вибрати зображення запуску.", noGameSelected: "Гру не вибрано.", launchStarting: "Запуск гри...", launchCheckingLicense: "Перевірка ліцензії...", launchCheckingFiles: "Перевірка файлів гри...", launchInstallingComponents: "Встановлення необхідних компонентів...", launchSyncingCloud: "Синхронізація Steam Cloud...", launchSyncingStats: "Синхронізація статистики...", launchSyncingController: "Завантаження конфігурації контролера...", launchPreparing: "Підготовка запуску...", launchDelayed: "Запуск затримано...", launchWaitingConfirmation: "Очікування підтвердження...", launchWaitingGame: "Очікування гри...", launchUpdating: "Оновлення гри..."
    },
    zh: {
        timeoutEnabled: "启用超时", modeAuto: "自动", forceMode: "强制模式", gameTimeout: "游戏超时", gameTimeoutSeconds: "游戏超时（秒）", timeoutHelp: "超时后自动隐藏启动幕布。", timeoutDisabledHelp: "启动幕布会保持显示，直到检测到游戏。", exitDelay: "退出延迟", exitDelayHelp: "检测到游戏后，让启动幕布继续显示一小段时间。",
        maintenance: "维护", refreshGameCache: "刷新游戏缓存", deleteUnusedImages: "删除未使用的图片", downloadPlayStationAssetsInstalled: "下载已安装游戏的 PS 素材", noInstalledGames: "未找到已安装的 Steam 游戏。", downloadPlayStationAssets: "下载 PlayStation 素材", removePlayStationAssets: "移除 PlayStation 素材", downloadingPlayStationAssets: "正在下载 PlayStation 素材", removingPlayStationAssets: "正在移除 PlayStation 素材", playStationBulkApplied: "已应用", playStationBulkRemoved: "已移除", playStationBulkSkipped: "已跳过", playStationBulkFailed: "失败", playStationBulkError: "无法完成 PlayStation 批量操作",
        tabGame: "游戏", tabAppearance: "外观", tabScrapers: "来源", gameBehavior: "Launch Curtain 行为", gameBehaviorHelp: "选择 Launch Curtain 对此游戏的行为。", enableForGame: "为此游戏启用 Launch Curtain", logoHelp: "管理游戏标志并打开可视化编辑器。", showLogo: "显示标志", openEditor: "打开编辑器", logoZoom: "启用标志放大动画", bgZoom: "启用背景缩小动画",
        launchImage: "启动图片", noLaunchImage: "未选择启动图片", chooseLaunchImage: "选择全屏启动图片", clearLaunchImage: "清除启动图片", editorTitle: "编辑器", close: "关闭", saving: "正在保存...", editorSaveFailed: "无法保存编辑器设置。", backgroundOpacity: "背景不透明度", logoShadowOpacity: "标志阴影不透明度", logoShadowBlur: "标志阴影模糊", up: "上", down: "下", left: "左", right: "右", reset: "重置", smaller: "缩小", bigger: "放大", cancel: "取消", save: "保存",
        downloadBackgrounds: "下载背景", scrapers: "背景来源", scrapersHelp: "选择一个来源，搜索游戏，然后选择背景。", searchQuery: "搜索内容", search: "搜索", searching: "正在搜索...", download: "下载", searchPlayStation: "搜索 PlayStation Store", searchingPlayStation: "正在搜索 PlayStation Store...", choosePlayStationGame: "选择匹配的 PlayStation 游戏。", playStationGame: "PlayStation 游戏", viewBackgrounds: "查看背景", loading: "正在加载...", backToResults: "返回结果", readingBackgrounds: "正在读取背景：", chooseBackground: "选择 PlayStation 背景。", noBackgrounds: "未找到合适的背景。", noPlayStationGames: "未在 PlayStation Store 中找到游戏。",
        background: "背景", gameWallpaper: "游戏壁纸", enterSearchQuery: "请输入搜索内容。", searchFailed: "无法完成搜索。", gameTitleUnavailable: "无法从 Steam 读取游戏标题。", imagesFound: "已找到图片。", noImagesFound: "未找到图片。", imageDownloaded: "启动图片已下载。", imageDownloadFailed: "无法下载图片。", chooseFileNotFolder: "请选择文件，而不是文件夹。", imagePickerFailed: "无法选择启动图片。", noGameSelected: "未选择游戏。", launchStarting: "正在启动游戏...", launchCheckingLicense: "正在检查许可证...", launchCheckingFiles: "正在检查游戏文件...", launchInstallingComponents: "正在安装所需组件...", launchSyncingCloud: "正在同步 Steam Cloud...", launchSyncingStats: "正在同步统计数据...", launchSyncingController: "正在加载控制器配置...", launchPreparing: "正在准备启动...", launchDelayed: "启动已延迟...", launchWaitingConfirmation: "正在等待确认...", launchWaitingGame: "正在等待游戏...", launchUpdating: "正在更新游戏..."
    },
    ja: {
        timeoutEnabled: "タイムアウトを有効化", modeAuto: "自動", forceMode: "モードを強制", gameTimeout: "ゲームのタイムアウト", gameTimeoutSeconds: "ゲームのタイムアウト（秒）", timeoutHelp: "タイムアウトするとカーテンを自動的に非表示にします。", timeoutDisabledHelp: "ゲームが検出されるまでカーテンを表示し続けます。", exitDelay: "終了遅延", exitDelayHelp: "ゲーム検出後もカーテンを少し長く表示します。",
        maintenance: "メンテナンス", refreshGameCache: "ゲームキャッシュを更新", deleteUnusedImages: "未使用の画像を削除", downloadPlayStationAssetsInstalled: "インストール済みゲームの PS アセットをダウンロード", noInstalledGames: "インストール済みの Steam ゲームが見つかりません。", downloadPlayStationAssets: "PlayStation アセットをダウンロード", removePlayStationAssets: "PlayStation アセットを削除", downloadingPlayStationAssets: "PlayStation アセットをダウンロード中", removingPlayStationAssets: "PlayStation アセットを削除中", playStationBulkApplied: "適用済み", playStationBulkRemoved: "削除済み", playStationBulkSkipped: "スキップ", playStationBulkFailed: "失敗", playStationBulkError: "PlayStation の一括処理を完了できませんでした",
        tabGame: "ゲーム", tabAppearance: "外観", tabScrapers: "ソース", gameBehavior: "Launch Curtain の動作", gameBehaviorHelp: "このゲームでの Launch Curtain の動作を選択します。", enableForGame: "このゲームで Launch Curtain を有効化", logoHelp: "ゲームロゴを管理し、ビジュアルエディターを開きます。", showLogo: "ロゴを表示", openEditor: "エディターを開く", logoZoom: "ロゴのズームインアニメーションを有効化", bgZoom: "背景のズームアウトアニメーションを有効化",
        launchImage: "起動画像", noLaunchImage: "起動画像が選択されていません", chooseLaunchImage: "全画面の起動画像を選択", clearLaunchImage: "起動画像を削除", editorTitle: "エディター", close: "閉じる", saving: "保存中...", editorSaveFailed: "エディター設定を保存できませんでした。", backgroundOpacity: "背景の不透明度", logoShadowOpacity: "ロゴ影の不透明度", logoShadowBlur: "ロゴ影のぼかし", up: "上", down: "下", left: "左", right: "右", reset: "リセット", smaller: "小さく", bigger: "大きく", cancel: "キャンセル", save: "保存",
        downloadBackgrounds: "背景をダウンロード", scrapers: "背景ソース", scrapersHelp: "ソースを選び、ゲームを検索してから背景を選択します。", searchQuery: "検索語", search: "検索", searching: "検索中...", download: "ダウンロード", searchPlayStation: "PlayStation Store を検索", searchingPlayStation: "PlayStation Store を検索中...", choosePlayStationGame: "一致する PlayStation ゲームを選択してください。", playStationGame: "PlayStation ゲーム", viewBackgrounds: "背景を表示", loading: "読み込み中...", backToResults: "結果に戻る", readingBackgrounds: "背景を読み込み中：", chooseBackground: "PlayStation の背景を選択してください。", noBackgrounds: "適切な背景が見つかりませんでした。", noPlayStationGames: "PlayStation Store にゲームが見つかりませんでした。",
        background: "背景", gameWallpaper: "ゲームの壁紙", enterSearchQuery: "検索語を入力してください。", searchFailed: "検索を完了できませんでした。", gameTitleUnavailable: "Steam からゲームタイトルを読み取れませんでした。", imagesFound: "画像が見つかりました。", noImagesFound: "画像が見つかりませんでした。", imageDownloaded: "起動画像をダウンロードしました。", imageDownloadFailed: "画像をダウンロードできませんでした。", chooseFileNotFolder: "フォルダーではなくファイルを選択してください。", imagePickerFailed: "起動画像を選択できませんでした。", noGameSelected: "ゲームが選択されていません。", launchStarting: "ゲームを起動中...", launchCheckingLicense: "ライセンスを確認中...", launchCheckingFiles: "ゲームファイルを確認中...", launchInstallingComponents: "必要なコンポーネントをインストール中...", launchSyncingCloud: "Steam Cloud を同期中...", launchSyncingStats: "統計を同期中...", launchSyncingController: "コントローラー設定を読み込み中...", launchPreparing: "起動を準備中...", launchDelayed: "起動が遅れています...", launchWaitingConfirmation: "確認を待っています...", launchWaitingGame: "ゲームを待っています...", launchUpdating: "ゲームを更新中..."
    }
};

function getLocaleKey() {
    const rawLanguage = navigator.language.toLowerCase();
    if (rawLanguage.startsWith("pt-br"))
        return "pt-br";
    if (rawLanguage.startsWith("zh"))
        return "zh";
    const baseLanguage = rawLanguage.split("-")[0];
    return I18N[baseLanguage] ? baseLanguage : "en";
}
function getStrings() {
    const locale = getLocaleKey();
    return { ...I18N.en, ...EXTRA_STRINGS.en, ...(I18N[locale] ?? {}), ...(EXTRA_STRINGS[locale] ?? {}), ...(EXTRA_TRANSLATIONS[locale] ?? {}) };
}

export { I18N, getStrings, getLocaleKey };
