// i18n e stringhe localizzate (11 lingue). Ricostruito dal dist.
const I18N = {
    en: {
        curtain: "Curtain",
        automation: "Settings",
        timeout: "Timeout",
        foreground: "Foreground",
        showCurtain: "Show curtain",
        hideCurtain: "Hide curtain",
        launchInfo: "Launch info",
        launchMode: "Launch mode",
        modeModern: "Modern (in Steam UI)",
        modeClassic: "Classic (overlay window)",
        modeOff: "Off",
        focusSteam: "Focus Steam",
        autoLaunchCurtain: "Enable launch screen",
        windowsOnly: "Windows-only backend. This system is not Windows.",
        noForeground: "No foreground window detected",
        logo: "Logo",
        chooseLogo: "Choose custom logo",
        useDefaultLogo: "Use default logo",
        defaultLogo: "Default Playhub logo",
        customLogo: "Custom logo",
        logoPickerError: "Could not choose a logo.",
        timeoutEnabled: "Enable timeout",
        timeoutHelp: "How long the launch screen can stay visible while waiting for the game to become fullscreen.",
        timeoutDisabledHelp: "When disabled, the launch screen hides only after fullscreen detection or manual close.",
        exitDelay: "Exit delay",
        exitDelayHelp: "How long Launch Curtain stays visible after detecting that the game is ready.",
        seconds25: "25 seconds",
        seconds45: "45 seconds",
        seconds75: "75 seconds",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain needs attention"
    },
    it: {
        curtain: "Schermata",
        automation: "Impostazioni",
        timeout: "Timeout",
        foreground: "Finestra attiva",
        showCurtain: "Mostra schermata",
        hideCurtain: "Nascondi schermata",
        launchInfo: "Informazioni di lancio",
        launchMode: "Modalità di avvio",
        modeModern: "Moderna (nella UI di Steam)",
        modeClassic: "Classica (finestra overlay)",
        modeOff: "Disattivata",
        focusSteam: "Riporta Steam davanti",
        autoLaunchCurtain: "Attiva la schermata di avvio",
        windowsOnly: "Backend solo per Windows. Questo sistema non e Windows.",
        noForeground: "Nessuna finestra attiva rilevata",
        logo: "Logo",
        chooseLogo: "Scegli logo custom",
        useDefaultLogo: "Usa logo predefinito",
        defaultLogo: "Logo Playhub predefinito",
        customLogo: "Logo custom",
        logoPickerError: "Non sono riuscito a scegliere un logo.",
        timeoutEnabled: "Attiva timeout",
        timeoutHelp: "Per quanto tempo la schermata di avvio puo restare visibile mentre aspetta che il gioco passi a schermo intero.",
        timeoutDisabledHelp: "Se disattivo, la schermata si chiude solo quando rileva il fullscreen o con la chiusura manuale.",
        exitDelay: "Ritardo uscita",
        exitDelayHelp: "Per quanto tempo Launch Curtain resta visibile dopo aver rilevato che il gioco e pronto.",
        seconds25: "25 secondi",
        seconds45: "45 secondi",
        seconds75: "75 secondi",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain richiede attenzione"
    },
    fr: {
        curtain: "Rideau",
        automation: "Automatisation",
        timeout: "Delai",
        foreground: "Fenetre active",
        showCurtain: "Afficher le rideau",
        hideCurtain: "Masquer le rideau",
        launchInfo: "Infos de lancement",
        launchMode: "Mode de lancement",
        modeModern: "Moderne (dans l'UI Steam)",
        modeClassic: "Classique (fenêtre overlay)",
        modeOff: "Désactivé",
        focusSteam: "Remettre Steam devant",
        autoLaunchCurtain: "Rideau automatique au lancement",
        windowsOnly: "Backend Windows uniquement. Ce systeme n'est pas Windows.",
        noForeground: "Aucune fenetre active detectee",
        logo: "Logo",
        chooseLogo: "Choisir un logo personnalise",
        useDefaultLogo: "Utiliser le logo par defaut",
        defaultLogo: "Logo Playhub par defaut",
        customLogo: "Logo personnalise",
        logoPickerError: "Impossible de choisir un logo.",
        seconds25: "25 secondes",
        seconds45: "45 secondes",
        seconds75: "75 secondes",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain demande votre attention"
    },
    es: {
        curtain: "Cortina",
        automation: "Automatizacion",
        timeout: "Tiempo limite",
        foreground: "Ventana activa",
        showCurtain: "Mostrar cortina",
        hideCurtain: "Ocultar cortina",
        launchInfo: "Información de inicio",
        launchMode: "Modo de inicio",
        modeModern: "Moderno (en la interfaz de Steam)",
        modeClassic: "Clásico (ventana superpuesta)",
        modeOff: "Desactivado",
        focusSteam: "Enfocar Steam",
        autoLaunchCurtain: "Cortina automatica al iniciar",
        windowsOnly: "Backend solo para Windows. Este sistema no es Windows.",
        noForeground: "No se detecto ninguna ventana activa",
        logo: "Logo",
        chooseLogo: "Elegir logo personalizado",
        useDefaultLogo: "Usar logo predeterminado",
        defaultLogo: "Logo Playhub predeterminado",
        customLogo: "Logo personalizado",
        logoPickerError: "No se pudo elegir un logo.",
        seconds25: "25 segundos",
        seconds45: "45 segundos",
        seconds75: "75 segundos",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain necesita atencion"
    },
    pt: {
        curtain: "Cortina",
        automation: "Automacao",
        timeout: "Tempo limite",
        foreground: "Janela ativa",
        showCurtain: "Mostrar cortina",
        hideCurtain: "Ocultar cortina",
        launchInfo: "Informações de inicialização",
        launchMode: "Modo de inicialização",
        modeModern: "Moderno (na interface do Steam)",
        modeClassic: "Clássico (janela sobreposta)",
        modeOff: "Desligado",
        focusSteam: "Focar Steam",
        autoLaunchCurtain: "Cortina automatica ao iniciar",
        windowsOnly: "Backend apenas para Windows. Este sistema nao e Windows.",
        noForeground: "Nenhuma janela ativa detectada",
        logo: "Logotipo",
        chooseLogo: "Escolher logotipo personalizado",
        useDefaultLogo: "Usar logotipo padrao",
        defaultLogo: "Logotipo Playhub padrao",
        customLogo: "Logotipo personalizado",
        logoPickerError: "Nao foi possivel escolher um logotipo.",
        seconds25: "25 segundos",
        seconds45: "45 segundos",
        seconds75: "75 segundos",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain precisa de atencao"
    },
    "pt-br": {
        curtain: "Cortina",
        automation: "Automacao",
        timeout: "Tempo limite",
        foreground: "Janela ativa",
        showCurtain: "Mostrar cortina",
        hideCurtain: "Ocultar cortina",
        launchInfo: "Informações de inicialização",
        launchMode: "Modo de inicialização",
        modeModern: "Moderno (na interface do Steam)",
        modeClassic: "Clássico (janela sobreposta)",
        modeOff: "Desligado",
        focusSteam: "Focar Steam",
        autoLaunchCurtain: "Cortina automatica ao iniciar",
        windowsOnly: "Backend apenas para Windows. Este sistema nao e Windows.",
        noForeground: "Nenhuma janela ativa detectada",
        logo: "Logo",
        chooseLogo: "Escolher logo personalizado",
        useDefaultLogo: "Usar logo padrao",
        defaultLogo: "Logo Playhub padrao",
        customLogo: "Logo personalizado",
        logoPickerError: "Nao foi possivel escolher um logo.",
        seconds25: "25 segundos",
        seconds45: "45 segundos",
        seconds75: "75 segundos",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain precisa de atencao"
    },
    de: {
        curtain: "Vorhang",
        automation: "Automatisierung",
        timeout: "Zeitlimit",
        foreground: "Aktives Fenster",
        showCurtain: "Vorhang anzeigen",
        hideCurtain: "Vorhang ausblenden",
        launchInfo: "Startinfos",
        launchMode: "Startmodus",
        modeModern: "Modern (in der Steam-UI)",
        modeClassic: "Klassisch (Overlay-Fenster)",
        modeOff: "Aus",
        focusSteam: "Steam fokussieren",
        autoLaunchCurtain: "Automatischer Startvorhang",
        windowsOnly: "Backend nur fur Windows. Dieses System ist nicht Windows.",
        noForeground: "Kein aktives Fenster erkannt",
        logo: "Logo",
        chooseLogo: "Eigenes Logo wahlen",
        useDefaultLogo: "Standardlogo verwenden",
        defaultLogo: "Standard-Playhub-Logo",
        customLogo: "Eigenes Logo",
        logoPickerError: "Logo konnte nicht ausgewahlt werden.",
        seconds25: "25 Sekunden",
        seconds45: "45 Sekunden",
        seconds75: "75 Sekunden",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain braucht Aufmerksamkeit"
    },
    nl: {
        curtain: "Gordijn",
        automation: "Automatisering",
        timeout: "Time-out",
        foreground: "Actief venster",
        showCurtain: "Gordijn tonen",
        hideCurtain: "Gordijn verbergen",
        launchInfo: "Startinfo",
        launchMode: "Startmodus",
        modeModern: "Modern (in Steam-UI)",
        modeClassic: "Klassiek (overlayvenster)",
        modeOff: "Uit",
        focusSteam: "Steam naar voren",
        autoLaunchCurtain: "Automatisch startgordijn",
        windowsOnly: "Backend alleen voor Windows. Dit systeem is geen Windows.",
        noForeground: "Geen actief venster gevonden",
        logo: "Logo",
        chooseLogo: "Eigen logo kiezen",
        useDefaultLogo: "Standaardlogo gebruiken",
        defaultLogo: "Standaard Playhub-logo",
        customLogo: "Eigen logo",
        logoPickerError: "Kon geen logo kiezen.",
        seconds25: "25 seconden",
        seconds45: "45 seconden",
        seconds75: "75 seconden",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain vraagt aandacht"
    },
    uk: {
        curtain: "Завіса",
        automation: "Автоматизація",
        timeout: "Час очікування",
        foreground: "Активне вікно",
        showCurtain: "Показати завісу",
        hideCurtain: "Сховати завісу",
        launchInfo: "Інформація про запуск",
        launchMode: "Режим запуску",
        modeModern: "Сучасний (в інтерфейсі Steam)",
        modeClassic: "Класичний (вікно-оверлей)",
        modeOff: "Вимкнено",
        focusSteam: "Повернути Steam на передній план",
        autoLaunchCurtain: "Автоматична завіса запуску",
        windowsOnly: "Backend працює лише у Windows. Ця система не Windows.",
        noForeground: "Активне вікно не знайдено",
        logo: "Логотип",
        chooseLogo: "Вибрати власний логотип",
        useDefaultLogo: "Використати типовий логотип",
        defaultLogo: "Типовий логотип Playhub",
        customLogo: "Власний логотип",
        logoPickerError: "Не вдалося вибрати логотип.",
        seconds25: "25 секунд",
        seconds45: "45 секунд",
        seconds75: "75 секунд",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain потребує уваги"
    },
    zh: {
        curtain: "启动幕布",
        automation: "自动化",
        timeout: "超时",
        foreground: "前台窗口",
        showCurtain: "显示幕布",
        hideCurtain: "隐藏幕布",
        launchInfo: "启动信息",
        launchMode: "启动模式",
        modeModern: "现代（Steam 界面内）",
        modeClassic: "经典（叠加窗口）",
        modeOff: "关闭",
        focusSteam: "聚焦 Steam",
        autoLaunchCurtain: "启动时自动显示幕布",
        windowsOnly: "后端仅支持 Windows。当前系统不是 Windows。",
        noForeground: "未检测到前台窗口",
        logo: "标志",
        chooseLogo: "选择自定义标志",
        useDefaultLogo: "使用默认标志",
        defaultLogo: "默认 Playhub 标志",
        customLogo: "自定义标志",
        logoPickerError: "无法选择标志。",
        seconds25: "25 秒",
        seconds45: "45 秒",
        seconds75: "75 秒",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain 需要注意"
    },
    ja: {
        curtain: "カーテン",
        automation: "自動化",
        timeout: "タイムアウト",
        foreground: "前面のウィンドウ",
        showCurtain: "カーテンを表示",
        hideCurtain: "カーテンを非表示",
        launchInfo: "起動情報",
        launchMode: "起動モード",
        modeModern: "モダン（Steam UI内）",
        modeClassic: "クラシック（オーバーレイ）",
        modeOff: "オフ",
        focusSteam: "Steam を前面へ",
        autoLaunchCurtain: "起動時に自動表示",
        windowsOnly: "バックエンドは Windows 専用です。このシステムは Windows ではありません。",
        noForeground: "前面のウィンドウが見つかりません",
        logo: "ロゴ",
        chooseLogo: "カスタムロゴを選択",
        useDefaultLogo: "既定のロゴを使用",
        defaultLogo: "既定の Playhub ロゴ",
        customLogo: "カスタムロゴ",
        logoPickerError: "ロゴを選択できませんでした。",
        seconds25: "25 秒",
        seconds45: "45 秒",
        seconds75: "75 秒",
        toastTitle: "Launch Curtain",
        toastAttention: "Launch Curtain に注意が必要です"
    }
};
const EXTRA_STRINGS = {
    en: {
        maintenance: "Maintenance", refreshGameCache: "Refresh game cache", deleteUnusedImages: "Delete unused images",
        downloadPlayStationAssets: "Download PlayStation assets", removePlayStationAssets: "Remove PlayStation assets", downloadingPlayStationAssets: "Downloading PlayStation assets", removingPlayStationAssets: "Removing PlayStation assets", playStationBulkApplied: "Applied", playStationBulkRemoved: "Removed", playStationBulkSkipped: "Skipped", playStationBulkFailed: "Failed", playStationBulkError: "The PlayStation bulk operation could not be completed",
        tabGame: "Game", tabAppearance: "Appearance", tabScrapers: "Scrapers",
        gameBehavior: "Launch Curtain behavior", gameBehaviorHelp: "Choose how Launch Curtain behaves for this game.", enableForGame: "Enable Launch Curtain for this game",
        logoHelp: "Control the game logo and open the visual editor.", showLogo: "Show logo", openEditor: "Open Editor", logoZoom: "Enable logo zoom-in animation", bgZoom: "Enable background zoom-out animation",
        launchImage: "Launch image", noLaunchImage: "No launch image selected", chooseLaunchImage: "Choose fullscreen launch image", clearLaunchImage: "Clear launch image",
        editorTitle: "Editor", close: "Close", saving: "Saving...", editorSaveFailed: "Could not save the editor settings.", backgroundOpacity: "Background opacity", logoShadowOpacity: "Logo shadow opacity", logoShadowBlur: "Logo shadow blur", up: "Up", down: "Down", left: "Left", right: "Right", reset: "Reset", smaller: "Smaller", bigger: "Bigger", cancel: "Cancel", save: "Save",
        downloadBackgrounds: "Download backgrounds", scrapers: "Background scrapers", scrapersHelp: "Choose one source, search for the game, then select a background.", searchQuery: "Search query", search: "Search", searching: "Searching...", download: "Download",
        searchPlayStation: "Search PlayStation Store", searchingPlayStation: "Searching PlayStation Store...", choosePlayStationGame: "Choose the matching PlayStation game.", playStationGame: "PlayStation game", viewBackgrounds: "View backgrounds", loading: "Loading...", backToResults: "Back to results", readingBackgrounds: "Reading backgrounds for", chooseBackground: "Choose a PlayStation background.", noBackgrounds: "No suitable backgrounds found.", noPlayStationGames: "No PlayStation Store games found.",
        background: "Background", gameWallpaper: "Game wallpaper", enterSearchQuery: "Enter a search query.", searchFailed: "The search could not be completed.", gameTitleUnavailable: "Could not read the game title from Steam.", imagesFound: "Images found.", noImagesFound: "No images found.", imageDownloaded: "Launch image downloaded.", imageDownloadFailed: "Could not download the image.", chooseFileNotFolder: "Choose a file, not a folder.", imagePickerFailed: "Could not choose a launch image.", noGameSelected: "No game selected.",
        launchStarting: "Starting game...", launchCheckingLicense: "Checking license...", launchCheckingFiles: "Checking game files...", launchInstallingComponents: "Installing required components...", launchSyncingCloud: "Synchronizing Steam Cloud...", launchSyncingStats: "Synchronizing statistics...", launchSyncingController: "Loading controller configuration...", launchPreparing: "Preparing launch...", launchDelayed: "Launch delayed...", launchWaitingConfirmation: "Waiting for confirmation...", launchWaitingGame: "Waiting for the game...", launchUpdating: "Updating game..."
    },
    it: {
        maintenance: "Manutenzione", refreshGameCache: "Aggiorna cache giochi", deleteUnusedImages: "Elimina immagini inutilizzate",
        downloadPlayStationAssets: "Scarica asset PlayStation", removePlayStationAssets: "Rimuovi asset PlayStation", downloadingPlayStationAssets: "Download asset PlayStation", removingPlayStationAssets: "Rimozione asset PlayStation", playStationBulkApplied: "Applicati", playStationBulkRemoved: "Rimossi", playStationBulkSkipped: "Saltati", playStationBulkFailed: "Non riusciti", playStationBulkError: "Non è stato possibile completare l'operazione PlayStation",
        tabGame: "Gioco", tabAppearance: "Aspetto", tabScrapers: "Scraper",
        gameBehavior: "Comportamento di Launch Curtain", gameBehaviorHelp: "Scegli come deve comportarsi Launch Curtain con questo gioco.", enableForGame: "Attiva Launch Curtain per questo gioco",
        logoHelp: "Gestisci il logo del gioco e apri l'editor visuale.", showLogo: "Mostra logo", openEditor: "Apri Editor", logoZoom: "Attiva animazione zoom-in del logo", bgZoom: "Attiva animazione zoom-out dello sfondo",
        launchImage: "Immagine di lancio", noLaunchImage: "Nessuna immagine di lancio selezionata", chooseLaunchImage: "Scegli immagine di lancio a schermo intero", clearLaunchImage: "Rimuovi immagine di lancio",
        editorTitle: "Editor", close: "Chiudi", saving: "Salvataggio...", editorSaveFailed: "Non è stato possibile salvare le impostazioni dell'editor.", backgroundOpacity: "Opacità dello sfondo", logoShadowOpacity: "Opacità ombra del logo", logoShadowBlur: "Blur ombra del logo", up: "Su", down: "Giù", left: "Sinistra", right: "Destra", reset: "Ripristina", smaller: "Più piccolo", bigger: "Più grande", cancel: "Annulla", save: "Salva",
        downloadBackgrounds: "Download sfondi", scrapers: "Scraper degli sfondi", scrapersHelp: "Scegli una sorgente, cerca il gioco e poi seleziona uno sfondo.", searchQuery: "Testo da cercare", search: "Cerca", searching: "Ricerca in corso...", download: "Scarica",
        searchPlayStation: "Cerca nel PlayStation Store", searchingPlayStation: "Ricerca nel PlayStation Store...", choosePlayStationGame: "Scegli il gioco PlayStation corretto.", playStationGame: "Gioco PlayStation", viewBackgrounds: "Vedi sfondi", loading: "Caricamento...", backToResults: "Torna ai risultati", readingBackgrounds: "Lettura degli sfondi per", chooseBackground: "Scegli uno sfondo PlayStation.", noBackgrounds: "Nessuno sfondo adatto trovato.", noPlayStationGames: "Nessun gioco trovato nel PlayStation Store.",
        background: "Sfondo", gameWallpaper: "Sfondo del gioco", enterSearchQuery: "Inserisci un testo da cercare.", searchFailed: "Non è stato possibile completare la ricerca.", gameTitleUnavailable: "Non è stato possibile leggere il titolo del gioco da Steam.", imagesFound: "Immagini trovate.", noImagesFound: "Nessuna immagine trovata.", imageDownloaded: "Immagine di lancio scaricata.", imageDownloadFailed: "Non è stato possibile scaricare l'immagine.", chooseFileNotFolder: "Scegli un file, non una cartella.", imagePickerFailed: "Non è stato possibile scegliere l'immagine di lancio.", noGameSelected: "Nessun gioco selezionato.",
        launchStarting: "Avvio del gioco...", launchCheckingLicense: "Verifica della licenza...", launchCheckingFiles: "Verifica dei file di gioco...", launchInstallingComponents: "Installazione dei componenti necessari...", launchSyncingCloud: "Sincronizzazione di Steam Cloud...", launchSyncingStats: "Sincronizzazione delle statistiche...", launchSyncingController: "Caricamento della configurazione controller...", launchPreparing: "Preparazione dell'avvio...", launchDelayed: "Avvio ritardato...", launchWaitingConfirmation: "In attesa di conferma...", launchWaitingGame: "In attesa del gioco...", launchUpdating: "Aggiornamento del gioco..."
    }
};
function getLocaleKey() {
    const rawLanguage = navigator.language.toLowerCase();
    if (rawLanguage.startsWith("pt-br"))
        return "pt-br";
    if (rawLanguage.startsWith("zh"))
        return "zh";
    const baseLanguage = rawLanguage.split("-")[0];
    return I18N[baseLanguage] ? baseLanguage : "en";
}
function getStrings() {
    const locale = getLocaleKey();
    return { ...I18N.en, ...EXTRA_STRINGS.en, ...(I18N[locale] ?? {}), ...(EXTRA_STRINGS[locale] ?? {}) };
}

export { I18N, getStrings, getLocaleKey };
